DBUG installation script
Update pip version to avoid crashes when installing snowtools as
editable with the following error :

  ERROR: Project file:///home/vernaym/snowtools has a 'pyproject.toml' and its
  build backend is missing the 'build_editable' hook.
  Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in
  editable mode. Consider using a build backend that supports PEP 660.